# @Author: Rafael Direito
# @Date:   2022-10-05 18:25:06 (WEST)
# @Email:  rdireito@av.it.pt
# @Copyright: Insituto de Telecomunicações - Aveiro, Aveiro, Portugal
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2022-10-05 18:26:15 (WEST)


version: "3.8"
services:
    alarm:
        build: .
        environment:
            - HOSTNAMERABBIT=rabbitmq3
        ports:
            - "8090:8090"

        restart: on-failure

        depends_on:
            - rabbitmq3
        links: 
            - rabbitmq3
            
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5



